project_id = "uoysmofeozdpygycioci"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]

[db]
enabled = true
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[functions.form-submission]
verify_jwt = false

[functions.admin-actions]
verify_jwt = true

[functions.google-sheets-integration]
verify_jwt = false

[functions.translate]
verify_jwt = false

[functions.batch-translate]
verify_jwt = false

[functions.security-headers]
verify_jwt = false